// <auto-generated />
using System;
using EmergencyAllocation.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EmergencyAllocation.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AllocationDbContext))]
    partial class AllocationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EmergencyAllocation.Core.Entities.AllocationVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DangerLevelRaised")
                        .HasColumnType("boolean");

                    b.Property<string>("InputVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsFeasible")
                        .HasColumnType("boolean");

                    b.Property<string>("NoFeasibleReason")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid?>("PreviousVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("SnapshotHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("SnapshotTakenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SolverVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long>("TotalCost")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("InputVersion")
                        .IsUnique();

                    b.ToTable("AllocationVersions");
                });

            modelBuilder.Entity("EmergencyAllocation.Core.Entities.AuditExplanation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AllocationVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("RelatedTaskId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RelatedTeamId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RuleCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("AllocationVersionId");

                    b.ToTable("AuditExplanations");
                });

            modelBuilder.Entity("EmergencyAllocation.Core.Entities.EmergencyTask", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("AssignedTeamId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("DangerLevel")
                        .HasColumnType("integer");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("LocationNode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("RequiredArrivalMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("RequiredCapabilities")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssignedTeamId");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("EmergencyAllocation.Core.Entities.RoadSegment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FromNode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("HeightLimitMeters")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ToNode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("TravelTimeMinutes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FromNode", "ToNode");

                    b.ToTable("RoadSegments");
                });

            modelBuilder.Entity("EmergencyAllocation.Core.Entities.TaskAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AllocationVersionId")
                        .HasColumnType("uuid");

                    b.Property<int>("EstimatedArrivalMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("EstimatedCompletionMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("PreemptionReason")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("RouteNodes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TeamId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("VehicleId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("AllocationVersionId");

                    b.ToTable("TaskAssignments");
                });

            modelBuilder.Entity("EmergencyAllocation.Core.Entities.Team", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Capabilities")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CurrentNode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("HomeNode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("VehicleId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("EmergencyAllocation.Core.Entities.Vehicle", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("HeightMeters")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("EmergencyAllocation.Core.Entities.AuditExplanation", b =>
                {
                    b.HasOne("EmergencyAllocation.Core.Entities.AllocationVersion", "AllocationVersion")
                        .WithMany("Explanations")
                        .HasForeignKey("AllocationVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AllocationVersion");
                });

            modelBuilder.Entity("EmergencyAllocation.Core.Entities.EmergencyTask", b =>
                {
                    b.HasOne("EmergencyAllocation.Core.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("AssignedTeamId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("EmergencyAllocation.Core.Entities.TaskAssignment", b =>
                {
                    b.HasOne("EmergencyAllocation.Core.Entities.AllocationVersion", "AllocationVersion")
                        .WithMany("Assignments")
                        .HasForeignKey("AllocationVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AllocationVersion");
                });

            modelBuilder.Entity("EmergencyAllocation.Core.Entities.Team", b =>
                {
                    b.HasOne("EmergencyAllocation.Core.Entities.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("EmergencyAllocation.Core.Entities.AllocationVersion", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Explanations");
                });
#pragma warning restore 612, 618
        }
    }
}
