// <auto-generated />
using System;
using EmergencyAllocation.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EmergencyAllocation.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AllocationDbContext))]
    partial class AllocationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EmergencyAllocation.Domain.AllocationAuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AllocationVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("allocation_version_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("message");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("entry_order");

                    b.Property<string>("RoadCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("road_code");

                    b.Property<string>("TaskCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("task_code");

                    b.Property<string>("TeamCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("team_code");

                    b.Property<string>("VehicleCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("vehicle_code");

                    b.HasKey("Id");

                    b.HasIndex("AllocationVersionId");

                    b.ToTable("allocation_audit_entries", (string)null);
                });

            modelBuilder.Entity("EmergencyAllocation.Domain.AllocationVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AssignedCount")
                        .HasColumnType("integer")
                        .HasColumnName("assigned_count");

                    b.Property<DateTimeOffset?>("CommittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("committed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("InputVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("input_version");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("operation");

                    b.Property<long?>("RoadSnapshotVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("road_snapshot_version");

                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Sequence"));

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TotalCostMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("total_cost_minutes");

                    b.Property<int>("UnassignedCount")
                        .HasColumnType("integer")
                        .HasColumnName("unassigned_count");

                    b.HasKey("Id");

                    b.HasIndex("Sequence");

                    b.HasIndex("Status");

                    b.HasIndex("Operation", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("allocation_versions", (string)null);
                });

            modelBuilder.Entity("EmergencyAllocation.Domain.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AllocationVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("allocation_version_id");

                    b.Property<int>("Decision")
                        .HasColumnType("integer")
                        .HasColumnName("decision");

                    b.Property<int>("EstimatedTotalMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_total_minutes");

                    b.Property<int>("EstimatedTravelMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_travel_minutes");

                    b.Property<bool>("MeetsDeadline")
                        .HasColumnType("boolean")
                        .HasColumnName("meets_deadline");

                    b.Property<bool>("Preempted")
                        .HasColumnType("boolean")
                        .HasColumnName("preempted");

                    b.Property<Guid?>("PreviousTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("previous_team_id");

                    b.Property<Guid?>("PreviousVehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("previous_vehicle_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("reason");

                    b.Property<string>("RouteNodeIds")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("route_node_ids");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<Guid?>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("AllocationVersionId");

                    b.HasIndex("TaskId");

                    b.HasIndex("TeamId");

                    b.HasIndex("VehicleId");

                    b.ToTable("assignments", (string)null);
                });

            modelBuilder.Entity("EmergencyAllocation.Domain.EmergencyTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_team_id");

                    b.Property<Guid?>("AssignedVehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_vehicle_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int?>("DeadlineMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("deadline_minutes");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<string>("LocationNodeId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("location_node_id");

                    b.Property<int>("Severity")
                        .HasColumnType("integer")
                        .HasColumnName("severity");

                    b.Property<int>("SeverityVersion")
                        .HasColumnType("integer")
                        .HasColumnName("severity_version");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("AssignedTeamId");

                    b.HasIndex("AssignedVehicleId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("emergency_tasks", (string)null);
                });

            modelBuilder.Entity("EmergencyAllocation.Domain.RoadSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<string>("FromNodeId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("from_node_id");

                    b.Property<double?>("HeightLimitMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("height_limit_meters");

                    b.Property<string>("InterruptionReason")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("interruption_reason");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("boolean")
                        .HasColumnName("is_open");

                    b.Property<long>("RoadSnapshotVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("snapshot_version");

                    b.Property<string>("ToNodeId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("to_node_id");

                    b.Property<int>("TravelTimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("travel_time_minutes");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("RoadSnapshotVersion");

                    b.ToTable("road_segments", (string)null);
                });

            modelBuilder.Entity("EmergencyAllocation.Domain.TaskCapabilityRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Capability")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("capability");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.HasKey("Id");

                    b.HasIndex("TaskId", "Capability")
                        .IsUnique();

                    b.ToTable("task_capability_requirements", (string)null);
                });

            modelBuilder.Entity("EmergencyAllocation.Domain.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BaseNodeId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("base_node_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("EmergencyAllocation.Domain.TeamCapability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Capability")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("capability");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("Id");

                    b.HasIndex("TeamId", "Capability")
                        .IsUnique();

                    b.ToTable("team_capabilities", (string)null);
                });

            modelBuilder.Entity("EmergencyAllocation.Domain.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("AverageSpeedMetersPerMinute")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_speed_m_per_min");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<double>("HeightMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("height_meters");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("TeamId");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("EmergencyAllocation.Domain.AllocationAuditEntry", b =>
                {
                    b.HasOne("EmergencyAllocation.Domain.AllocationVersion", "AllocationVersion")
                        .WithMany("AuditEntries")
                        .HasForeignKey("AllocationVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AllocationVersion");
                });

            modelBuilder.Entity("EmergencyAllocation.Domain.Assignment", b =>
                {
                    b.HasOne("EmergencyAllocation.Domain.AllocationVersion", "AllocationVersion")
                        .WithMany("Assignments")
                        .HasForeignKey("AllocationVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmergencyAllocation.Domain.EmergencyTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmergencyAllocation.Domain.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId");

                    b.HasOne("EmergencyAllocation.Domain.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId");

                    b.Navigation("AllocationVersion");

                    b.Navigation("Task");

                    b.Navigation("Team");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("EmergencyAllocation.Domain.EmergencyTask", b =>
                {
                    b.HasOne("EmergencyAllocation.Domain.Team", "AssignedTeam")
                        .WithMany()
                        .HasForeignKey("AssignedTeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EmergencyAllocation.Domain.Vehicle", "AssignedVehicle")
                        .WithMany()
                        .HasForeignKey("AssignedVehicleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedTeam");

                    b.Navigation("AssignedVehicle");
                });

            modelBuilder.Entity("EmergencyAllocation.Domain.TaskCapabilityRequirement", b =>
                {
                    b.HasOne("EmergencyAllocation.Domain.EmergencyTask", "Task")
                        .WithMany("RequiredCapabilities")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("EmergencyAllocation.Domain.TeamCapability", b =>
                {
                    b.HasOne("EmergencyAllocation.Domain.Team", "Team")
                        .WithMany("Capabilities")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("EmergencyAllocation.Domain.Vehicle", b =>
                {
                    b.HasOne("EmergencyAllocation.Domain.Team", "Team")
                        .WithMany("Vehicles")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("EmergencyAllocation.Domain.AllocationVersion", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("AuditEntries");
                });

            modelBuilder.Entity("EmergencyAllocation.Domain.EmergencyTask", b =>
                {
                    b.Navigation("RequiredCapabilities");
                });

            modelBuilder.Entity("EmergencyAllocation.Domain.Team", b =>
                {
                    b.Navigation("Capabilities");

                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
