// <auto-generated />
using System;
using EmergencyDispatch.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EmergencyDispatch.Infrastructure.Migrations
{
    [DbContext(typeof(DispatchDbContext))]
    partial class DispatchDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EmergencyDispatch.Domain.AllocationBaseline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AllocationVersionId")
                        .HasColumnType("uuid");

                    b.Property<int>("DangerLevel")
                        .HasColumnType("integer");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AllocationVersionId", "TaskId")
                        .IsUnique();

                    b.ToTable("AllocationBaselines");
                });

            modelBuilder.Entity("EmergencyDispatch.Domain.AllocationVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasUnassignedTasks")
                        .HasColumnType("boolean");

                    b.Property<string>("InputVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalCostMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InputVersion")
                        .IsUnique();

                    b.HasIndex("VersionNumber")
                        .IsUnique();

                    b.ToTable("AllocationVersions");
                });

            modelBuilder.Entity("EmergencyDispatch.Domain.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AllocationVersionId")
                        .HasColumnType("uuid");

                    b.Property<int>("ArrivalMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("RoadSegmentCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoadSegmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("TaskCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("TeamCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<string>("VehicleCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AllocationVersionId");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("EmergencyDispatch.Domain.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AllocationVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RuleCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<string>("TaskCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AllocationVersionId");

                    b.ToTable("AuditEntries");
                });

            modelBuilder.Entity("EmergencyDispatch.Domain.MissionTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DangerLevel")
                        .HasColumnType("integer");

                    b.Property<int>("DeadlineMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ExecutingTeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ExecutingVehicleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequiredCapabilities")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ServiceMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("EmergencyDispatch.Domain.RoadSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("HeightLimitMeters")
                        .HasColumnType("numeric(4,2)");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("RoadSegments");
                });

            modelBuilder.Entity("EmergencyDispatch.Domain.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoadSegmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<int>("TravelMinutes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TaskId", "RoadSegmentId")
                        .IsUnique();

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("EmergencyDispatch.Domain.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Capabilities")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("EmergencyDispatch.Domain.UnassignedReason", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AllocationVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaskCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AllocationVersionId");

                    b.ToTable("UnassignedReasons");
                });

            modelBuilder.Entity("EmergencyDispatch.Domain.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("HeightMeters")
                        .HasColumnType("numeric(4,2)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("EmergencyDispatch.Domain.AllocationBaseline", b =>
                {
                    b.HasOne("EmergencyDispatch.Domain.AllocationVersion", null)
                        .WithMany("Baselines")
                        .HasForeignKey("AllocationVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EmergencyDispatch.Domain.Assignment", b =>
                {
                    b.HasOne("EmergencyDispatch.Domain.AllocationVersion", null)
                        .WithMany("Assignments")
                        .HasForeignKey("AllocationVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EmergencyDispatch.Domain.AuditEntry", b =>
                {
                    b.HasOne("EmergencyDispatch.Domain.AllocationVersion", null)
                        .WithMany("AuditEntries")
                        .HasForeignKey("AllocationVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EmergencyDispatch.Domain.UnassignedReason", b =>
                {
                    b.HasOne("EmergencyDispatch.Domain.AllocationVersion", null)
                        .WithMany("UnassignedReasons")
                        .HasForeignKey("AllocationVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EmergencyDispatch.Domain.AllocationVersion", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("AuditEntries");

                    b.Navigation("Baselines");

                    b.Navigation("UnassignedReasons");
                });
#pragma warning restore 612, 618
        }
    }
}
